[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"


[project]
name = "hammers"
version = "0.0.1"
authors = [{ name = "Chameleon Team", email = "help@chameleoncloud.org" }]
description = 'Bag of hammers to fix problems'
readme = "README.rst"
requires-python = ">=3.8"
classifiers = [
    'Development Status :: 4 - Beta',
    'Environment :: OpenStack',
    'Intended Audience :: System Administrators',
    'Topic :: Utilities',
]

dependencies = [
  "openstacksdk",
  "python-ironicclient",
  "python-blazarclient @ git+https://github.com/chameleonCloud/python-blazarclient"
]

[project.urls]
Homepage = 'https://github.com/ChameleonCloud/hammers'
